
[build]
  command = "pnpm install --prod && pnpm build"
  publish = "apps/web/.next" # Default publish directory, can be overridden in Netlify UI

[build.environment]
  # Set the Node.js version to match your project
  NODE_VERSION = "20"

# Redirects and headers can be configured here if needed
