blank_issues_enabled: false
contact_links:
  - name: Ask a question
    url: https://github.com/your-org/your-repo/discussions/new?category=q-a
    about: Ask and answer questions here.
  - name: Feature request
    url: https://github.com/your-org/your-repo/discussions/new?category=ideas
    about: Share ideas for new features.
