'use client';

import { useState, useEffect } from 'react';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';
import { summarizeClusterHealth } from '@/ai/flows/summarize-cluster-health';
import type { Cluster } from '@/lib/types';
import { mockAlerts } from '@/lib/mock-data';
import { Skeleton } from '@/components/ui/skeleton';
import { Bot } from 'lucide-react';

interface ClusterHealthSummaryProps {
  cluster: Cluster;
}

export function ClusterHealthSummary({ cluster }: ClusterHealthSummaryProps) {
  const [summary, setSummary] = useState<string>('');
  const [loading, setLoading] = useState<boolean>(true);

  useEffect(() => {
    async function getSummary() {
      try {
        setLoading(true);
        const clusterAlerts = mockAlerts.filter((a) => a.clusterId === cluster.id);
        const result = await summarizeClusterHealth({
          clusterName: cluster.name,
          healthMetrics: JSON.stringify(cluster.healthMetrics),
          alerts: JSON.stringify(clusterAlerts),
        });
        setSummary(result.summary);
      } catch (error) {
        console.error('Error fetching cluster health summary:', error);
        setSummary('Could not generate health summary at this time.');
      } finally {
        setLoading(false);
      }
    }
    if (cluster) {
      getSummary();
    }
  }, [cluster]);

  return (
    <Card>
      <CardHeader>
        <div className="flex items-center gap-2">
          <Bot className="h-6 w-6 text-primary" />
          <CardTitle>AI Health Summary: {cluster.name}</CardTitle>
        </div>
        <CardDescription>
          This summary is automatically generated by AI to highlight key issues.
        </CardDescription>
      </CardHeader>
      <CardContent>
        {loading ? (
          <div className="space-y-2">
            <Skeleton className="h-4 w-full" />
            <Skeleton className="h-4 w-full" />
            <Skeleton className="h-4 w-3/4" />
          </div>
        ) : (
          <p className="text-sm text-muted-foreground">{summary}</p>
        )}
      </CardContent>
    </Card>
  );
}
